server:
  port: 3012
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    preferIpAddress: true
spring:
  application:
    name: config-eureka-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiezhixiankevin/shipping-config
          username: xiezhixiankevin
          password: shiwo2002625
          default-label: master
          search-paths: config